"""Render deterministic placeholder files for the phase-1 Ren'Py scaffold."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from .constants import ASSET_DIRECTORIES, FUTURE_TEMPLATE_ROOT, GENERATED_README_NAME
from .manifest import ProjectManifest


@dataclass(frozen=True, slots=True)
class RenderedFile:
    relative_path: Path
    content: str


def build_render_plan(manifest: ProjectManifest) -> tuple[RenderedFile, ...]:
    return (
        RenderedFile(Path(GENERATED_README_NAME), _render_generated_readme(manifest)),
        RenderedFile(Path("game") / "options.rpy", _render_options(manifest)),
        RenderedFile(Path("game") / "gui.rpy", _render_gui(manifest)),
        RenderedFile(Path("game") / "00_bootstrap.rpy", _render_bootstrap(manifest)),
        RenderedFile(Path("game") / "10_characters.rpy", _render_characters()),
        RenderedFile(Path("game") / "20_audio.rpy", _render_audio()),
        RenderedFile(Path("game") / "30_transforms.rpy", _render_transforms()),
        RenderedFile(Path("game") / "40_screens_main_menu.rpy", _render_main_menu()),
        RenderedFile(Path("game") / "41_screens_hud.rpy", _render_hud()),
        RenderedFile(Path("game") / "42_screens_save_load.rpy", _render_save_load(manifest)),
        RenderedFile(Path("game") / "43_screens_preferences.rpy", _render_preferences()),
        RenderedFile(Path("game") / "44_screens_history.rpy", _render_history(manifest)),
        RenderedFile(Path("game") / "45_screens_confirm.rpy", _render_confirm()),
        RenderedFile(Path("game") / "50_script_prologue.rpy", _render_prologue()),
        *(RenderedFile(path / ".gitkeep", "") for path in ASSET_DIRECTORIES),
    )


def write_render_plan(
    output_dir: Path,
    render_plan: Iterable[RenderedFile],
    *,
    force: bool = False,
) -> tuple[Path, ...]:
    written_files: list[Path] = []

    for rendered_file in render_plan:
        destination = output_dir / rendered_file.relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)

        if destination.exists() and destination.is_dir():
            raise IsADirectoryError(f"Refusing to overwrite directory with file: {destination}")

        if destination.exists() and not force:
            raise FileExistsError(f"Refusing to overwrite existing file: {destination}")

        with destination.open("w", encoding="utf-8", newline="\n") as handle:
            handle.write(rendered_file.content)

        written_files.append(destination)

    return tuple(written_files)


def _render_generated_readme(manifest: ProjectManifest) -> str:
    source_name = manifest.source_path.name if manifest.source_path else "manifest.toml"
    return f"""# {manifest.project.window_title}

This directory was generated by the phase-1 `galgame_template` scaffold from `{source_name}`.

The generated `.rpy` files are placeholder contract files, not final visual production assets.
They exist so the repo can express the non-visual runtime foundation described in `docs/项目程序需求.txt`
without requiring a local Ren'Py SDK.

## Captured baseline

- save pages: {manifest.ui.save_pages}
- slots per page: {manifest.ui.slots_per_page}
- total save slots: {manifest.ui.save_slot_count}
- auto forward seconds: {manifest.ui.default_auto_forward_seconds}
- seconds per character: {manifest.ui.default_seconds_per_char}
- history length: {manifest.ui.history_length}

Future polished template assets can replace these files later via `{FUTURE_TEMPLATE_ROOT.as_posix()}`.
"""


def _render_options(manifest: ProjectManifest) -> str:
    return f"""# Phase 1 placeholder options scaffold

define config.name = _("{manifest.project.window_title}")
define config.version = "{manifest.project.version}"
define build.name = "{manifest.project.slug}"

default phase1_save_pages = {manifest.ui.save_pages}
default phase1_slots_per_page = {manifest.ui.slots_per_page}
default phase1_history_length = {manifest.ui.history_length}
"""


def _render_gui(manifest: ProjectManifest) -> str:
    return f"""# Phase 1 placeholder GUI contract for {manifest.project.window_title}
# Later visual passes can replace these styles with polished assets and transitions.

style phase1_menu_button is default:
    padding (18, 10)

transform hover_pulse:
    linear 0.10 zoom 1.03
    linear 0.10 zoom 1.0
"""


def _render_bootstrap(manifest: ProjectManifest) -> str:
    return f"""# Runtime helpers for the generated phase-1 scaffold

default custom_auto_forward_seconds = {manifest.ui.default_auto_forward_seconds}
default custom_seconds_per_char = {manifest.ui.default_seconds_per_char}
default custom_text_cps = {manifest.ui.default_text_cps}
default interface_hidden = False
default auto_mode_enabled = False

init python:
    def toggle_interface():
        renpy.store.interface_hidden = not renpy.store.interface_hidden

    def set_auto_forward_seconds(value):
        renpy.store.custom_auto_forward_seconds = float(value)

    def set_text_seconds_per_char(value):
        numeric = max(0.01, float(value))
        renpy.store.custom_seconds_per_char = numeric
        renpy.store.custom_text_cps = max(1, int(round(1.0 / numeric)))

    def start_auto_mode():
        renpy.store.auto_mode_enabled = True

    def stop_auto_mode():
        renpy.store.auto_mode_enabled = False

    def save_or_confirm(slot_name):
        if renpy.slot_json(slot_name):
            renpy.show_screen("confirm_save_overwrite", slot_name)
        else:
            renpy.save(slot_name)

    def overwrite_save(slot_name):
        renpy.save(slot_name)
"""


def _render_characters() -> str:
    return """# Placeholder character and image declarations for the vertical slice

define narrator = Character(None)
define hero = Character("Hero")

image bg demo_room = Solid("#162033")
image char hero default = Solid("#4f7195", xysize=(700, 1000))
"""


def _render_audio() -> str:
    return """# Audio helper hooks for the phase-1 scaffold

define audio.ui_click = "audio/sfx/ui_click.wav"

init python:
    def safe_play_music(filename, fadein=0.0):
        if renpy.loadable(filename):
            renpy.music.play(filename, channel="music", loop=True, fadein=fadein)

    def safe_play_voice(filename):
        if renpy.loadable(filename):
            renpy.sound.play(filename, channel="voice")

    def safe_play_ui_click():
        if renpy.loadable(audio.ui_click):
            renpy.sound.play(audio.ui_click, channel="sound")
"""


def _render_transforms() -> str:
    return """# Placeholder transitions and transforms aligned with the runtime requirements

define bg_fade = Dissolve(0.40)
define bg_dissolve = Dissolve(0.25)

transform char_move_in_left:
    xalign -0.25
    linear 0.50 xalign 0.5

transform char_shake:
    linear 0.05 xoffset -12
    linear 0.05 xoffset 12
    linear 0.05 xoffset -8
    linear 0.05 xoffset 8
    linear 0.05 xoffset 0

transform char_zoom_pulse:
    zoom 1.0
    linear 0.12 zoom 1.04
    linear 0.12 zoom 1.0
"""


def _render_main_menu() -> str:
    return """screen main_menu():
    tag menu

    add Solid("#10151c")

    frame:
        xalign 0.5
        yalign 0.5

        vbox:
            spacing 18

            textbutton _("Start") action Start()
            textbutton _("Load") action ShowMenu("load")
            textbutton _("Settings") action ShowMenu("preferences")
            textbutton _("Exit") action ShowMenu("confirm_exit")
"""


def _render_hud() -> str:
    return """screen game_hud():
    key "mouseup_3" action Function(toggle_interface)

    if not interface_hidden:
        frame:
            xalign 0.5
            yalign 0.96

            hbox:
                spacing 12

                textbutton _("SAVE") action ShowMenu("save")
                textbutton _("LOAD") action ShowMenu("load")
                textbutton _("CONFIG") action ShowMenu("preferences")
                textbutton _("EXIT") action ShowMenu("confirm_exit")
                textbutton _("History") action ShowMenu("history_log")
                textbutton _("Auto") action Function(start_auto_mode)
                textbutton _("Pause") action Function(stop_auto_mode)
"""


def _render_save_load(manifest: ProjectManifest) -> str:
    return f"""screen save():
    tag menu
    use file_slot_grid("save")


screen load():
    tag menu
    use file_slot_grid("load")


screen file_slot_grid(mode):
    default total_slots = {manifest.ui.save_slot_count}

    viewport:
        scrollbars "vertical"
        mousewheel True

        grid 1 total_slots:
            spacing 8

            for slot_index in range(1, total_slots + 1):
                $ slot_name = str(slot_index)

                button:
                    if mode == "save":
                        action Function(save_or_confirm, slot_name)
                    else:
                        action FileAction(slot_name)

                    vbox:
                        text _("Slot {{slot}}".format(slot=slot_index))
                        text FileTime(slot_name, format="%Y-%m-%d %H:%M", empty=_('Empty'))
"""


def _render_preferences() -> str:
    return """screen preferences():
    tag menu

    frame:
        xalign 0.5
        yalign 0.5

        vbox:
            spacing 12

            bar value Preference("music volume")
            bar value Preference("voice volume")
            bar value Preference("sound volume")

            bar value VariableValue("custom_auto_forward_seconds", 1.0, 30.0, step=0.5)
            bar value VariableValue("custom_seconds_per_char", 0.01, 0.50, step=0.01)

            textbutton _("Apply Auto Speed") action Function(set_auto_forward_seconds, custom_auto_forward_seconds)
            textbutton _("Apply Text Speed") action Function(set_text_seconds_per_char, custom_seconds_per_char)
"""


def _render_history(manifest: ProjectManifest) -> str:
    return f"""screen history_log():
    tag menu

    frame:
        xalign 0.5
        yalign 0.5

        viewport:
            scrollbars "vertical"
            mousewheel True
            draggable True

            vbox:
                for history_entry in _history_list[-{manifest.ui.history_length}:]:
                    text history_entry.what
"""


def _render_confirm() -> str:
    return """screen confirm_exit():
    modal True

    frame:
        xalign 0.5
        yalign 0.5

        vbox:
            spacing 12

            text _("Exit the game?")
            textbutton _("Exit") action Quit(confirm=False)
            textbutton _("Cancel") action Hide("confirm_exit")


screen confirm_save_overwrite(slot_name):
    modal True

    frame:
        xalign 0.5
        yalign 0.5

        vbox:
            spacing 12

            text _("Overwrite")
            text _("Overwrite save slot [slot_name]?")
            textbutton _("Overwrite") action [Function(overwrite_save, slot_name), Hide("confirm_save_overwrite")]
            textbutton _("Cancel") action Hide("confirm_save_overwrite")
"""


def _render_prologue() -> str:
    return """label start:
    scene bg demo_room with bg_fade
    show char hero default at char_move_in_left

    $ safe_play_music("audio/music/demo_bgm.mp3", fadein=1.0)
    hero "The phase-1 scaffold is alive."

    $ safe_play_voice("audio/voice/hero_001.wav")
    hero "This vertical slice wires menus, save hooks, history, autoplay settings, and placeholder animation seams."

    menu:
        "Open the system demo.":
            jump system_demo
        "End the slice.":
            return


label system_demo:
    hero "Use SAVE, LOAD, CONFIG, EXIT, History, Auto, and Pause from the generated HUD placeholders."
    return
"""
