"""Render deterministic placeholder files for the phase-1 Ren'Py scaffold."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from .constants import ASSET_DIRECTORIES, FUTURE_TEMPLATE_ROOT, GENERATED_README_NAME
from .manifest import ProjectManifest


@dataclass(frozen=True, slots=True)
class RenderedFile:
    relative_path: Path
    content: str


def build_render_plan(manifest: ProjectManifest) -> tuple[RenderedFile, ...]:
    return (
        RenderedFile(Path(GENERATED_README_NAME), _render_generated_readme(manifest)),
        RenderedFile(Path("game") / "options.rpy", _render_options(manifest)),
        RenderedFile(Path("game") / "gui.rpy", _render_gui(manifest)),
        RenderedFile(Path("game") / "00_bootstrap.rpy", _render_bootstrap(manifest)),
        RenderedFile(Path("game") / "10_characters.rpy", _render_characters()),
        RenderedFile(Path("game") / "20_audio.rpy", _render_audio()),
        RenderedFile(Path("game") / "30_transforms.rpy", _render_transforms()),
        RenderedFile(Path("game") / "40_screens_main_menu.rpy", _render_main_menu()),
        RenderedFile(Path("game") / "41_screens_say.rpy", _render_say(manifest)),
        RenderedFile(Path("game") / "42_screens_hud.rpy", _render_hud()),
        RenderedFile(Path("game") / "43_screens_save_load.rpy", _render_save_load(manifest)),
        RenderedFile(Path("game") / "44_screens_preferences.rpy", _render_preferences()),
        RenderedFile(Path("game") / "45_screens_history.rpy", _render_history(manifest)),
        RenderedFile(Path("game") / "46_screens_confirm.rpy", _render_confirm()),
        RenderedFile(Path("game") / "50_script_prologue.rpy", _render_prologue()),
        *(RenderedFile(path / ".gitkeep", "") for path in ASSET_DIRECTORIES),
    )


def write_render_plan(
    output_dir: Path,
    render_plan: Iterable[RenderedFile],
    *,
    force: bool = False,
) -> tuple[Path, ...]:
    written_files: list[Path] = []

    for rendered_file in render_plan:
        destination = output_dir / rendered_file.relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)

        if destination.exists() and destination.is_dir():
            raise IsADirectoryError(f"Refusing to overwrite directory with file: {destination}")

        if destination.exists() and not force:
            raise FileExistsError(f"Refusing to overwrite existing file: {destination}")

        with destination.open("w", encoding="utf-8", newline="\n") as handle:
            handle.write(rendered_file.content)

        written_files.append(destination)

    return tuple(written_files)


def _render_generated_readme(manifest: ProjectManifest) -> str:
    source_name = manifest.source_path.name if manifest.source_path else "manifest.toml"
    return f"""# {manifest.project.window_title}

This directory was generated by the phase-1 `galgame_template` scaffold from `{source_name}`.

The generated `.rpy` files are placeholder contract files, not final visual production assets.
They exist so the repo can express the non-visual runtime foundation described in `docs/项目程序需求.txt`
without requiring a local Ren'Py SDK.

## Captured baseline

- save pages: {manifest.ui.save_pages}
- slots per page: {manifest.ui.slots_per_page}
- total save slots: {manifest.ui.save_slot_count}
- auto forward seconds: {manifest.ui.default_auto_forward_seconds}
- seconds per character: {manifest.ui.default_seconds_per_char}
- history length: {manifest.ui.history_length}

Future polished template assets can replace these files later via `{FUTURE_TEMPLATE_ROOT.as_posix()}`.
"""


def _render_options(manifest: ProjectManifest) -> str:
    return f"""# Phase 1 placeholder options scaffold

define config.name = _("{manifest.project.window_title}")
define config.version = "{manifest.project.version}"
define build.name = "{manifest.project.slug}"

define config.screen_width = 1920
define config.screen_height = 1080

default phase1_save_pages = {manifest.ui.save_pages}
default phase1_slots_per_page = {manifest.ui.slots_per_page}
default phase1_history_length = {manifest.ui.history_length}
"""


def _render_gui(manifest: ProjectManifest) -> str:
    return f"""# Phase 1 placeholder GUI contract for {manifest.project.window_title}
# Later visual passes can replace these styles with polished assets and transitions.

init offset = -2

init python:
    gui.init(1920, 1080)

# 中文字体支持
style default:
    font "fonts/msyh.ttc"

# 对话框背景（使用 textbox.png 图片）
style say_window:
    background Frame("images/ui/textbox.png", 60, 30, 60, 30)
    xalign 0.5
    yalign 1.0
    xfill True
    yminimum 220
    padding (60, 30)

# 角色名框
style say_namebox:
    background Solid("#2a3040")
    xalign 0.0
    yalign 0.0
    padding (16, 8)

style namebox:
    background Solid("#2a3040")
    xalign 0.0
    yalign 0.0
    padding (16, 8)

# 角色名文字
style say_who:
    font "fonts/msyh.ttc"
    color "#88ccff"
    size {manifest.ui.name_text_size if hasattr(manifest.ui, 'name_text_size') else 26}
    bold True

# 对话文字
style say_what:
    font "fonts/msyh.ttc"
    color "#ffffff"
    size {manifest.ui.dialogue_text_size if hasattr(manifest.ui, 'dialogue_text_size') else 28}
    line_spacing 8

style say_label:
    font "fonts/msyh.ttc"
    color "#88ccff"
    size {manifest.ui.name_text_size if hasattr(manifest.ui, 'name_text_size') else 26}

style say_dialogue:
    font "fonts/msyh.ttc"
    color "#ffffff"
    size {manifest.ui.dialogue_text_size if hasattr(manifest.ui, 'dialogue_text_size') else 28}

style button_text:
    font "fonts/msyh.ttc"

style text:
    font "fonts/msyh.ttc"

style phase1_menu_button is default:
    padding (18, 10)

# Image button style with sound effects
style imagebutton:
    activate_sound "audio/sfx/ui_click.wav"
    hover_sound "audio/sfx/ui_hover.wav"

transform hover_pulse:
    linear 0.10 zoom 1.03
    linear 0.10 zoom 1.0
"""


def _render_bootstrap(manifest: ProjectManifest) -> str:
    return f"""# Runtime helpers for the generated phase-1 scaffold

default custom_auto_forward_seconds = {manifest.ui.default_auto_forward_seconds}
default custom_seconds_per_char = {manifest.ui.default_seconds_per_char}
default custom_text_cps = {manifest.ui.default_text_cps}
default interface_hidden = False
default auto_mode_enabled = False

init python:
    def toggle_interface():
        renpy.store.interface_hidden = not renpy.store.interface_hidden

    def set_auto_forward_seconds(value):
        renpy.store.custom_auto_forward_seconds = float(value)
        renpy.game.preferences.afm_time = float(value)

    def set_text_seconds_per_char(value):
        numeric = max(0.01, float(value))
        renpy.store.custom_seconds_per_char = numeric
        renpy.store.custom_text_cps = max(1, int(round(1.0 / numeric)))
        renpy.game.preferences.text_cps = renpy.store.custom_text_cps

    def start_auto_mode():
        renpy.store.auto_mode_enabled = True

    def stop_auto_mode():
        renpy.store.auto_mode_enabled = False

    def save_or_confirm(slot_name):
        if renpy.slot_json(slot_name):
            renpy.show_screen("confirm_save_overwrite", slot_name)
        else:
            renpy.save(slot_name)

    def overwrite_save(slot_name):
        renpy.save(slot_name)
"""


def _render_characters() -> str:
    return """# Placeholder character and image declarations for the vertical slice
# Replace image paths with your actual asset files.

define narrator = Character(None)
define hero = Character("Hero")

# Example: define your characters and map them to images in images/characters/
# define protagonist = Character("主角")
# define sidekick = Character("夏百咲")

image bg demo_room = Solid("#162033")
# image bg meeting_room = "images/backgrounds/场景_会议室.png"

image char hero default = Solid("#4f7195", xysize=(700, 1000))
# image protagonist = "images/characters/柊春雪.png"
# image sidekick = "images/characters/夏百咲.png"
"""


def _render_audio() -> str:
    return """# Audio helper hooks for the phase-1 scaffold

define audio.ui_click = "audio/sfx/ui_click.wav"

init python:
    def safe_play_music(filename, fadein=0.0):
        if renpy.loadable(filename):
            renpy.music.play(filename, channel="music", loop=True, fadein=fadein)

    def safe_play_voice(filename):
        if renpy.loadable(filename):
            renpy.sound.play(filename, channel="voice")

    def safe_play_ui_click():
        if renpy.loadable(audio.ui_click):
            renpy.sound.play(audio.ui_click, channel="sound")
"""


def _render_transforms() -> str:
    return """# Placeholder transitions and transforms aligned with the runtime requirements

define bg_fade = Dissolve(0.40)
define bg_dissolve = Dissolve(0.25)

# Character positions (xalign: 0=left, 0.5=center, 1=right; yalign: 0=top, 1=bottom)
transform pos_left:
    xalign 0.15
    yalign -0.02

transform pos_center:
    xalign 0.5
    yalign -0.02

transform pos_right:
    xalign 0.85
    yalign -0.02

transform pos_far_left:
    xalign 0.0
    yalign -0.02

transform pos_far_right:
    xalign 1.0
    yalign -0.02

# Character scaling
transform scale_small:
    zoom 0.8
    yalign 1.0

transform scale_large:
    zoom 1.2
    yalign 1.0

# Animation transforms
transform char_move_in_left:
    xalign -0.25
    linear 0.50 xalign 0.5

transform char_shake:
    linear 0.05 xoffset -12
    linear 0.05 xoffset 12
    linear 0.05 xoffset -8
    linear 0.05 xoffset 8
    linear 0.05 xoffset 0

transform char_zoom_pulse:
    zoom 1.0
    linear 0.12 zoom 1.04
    linear 0.12 zoom 1.0
"""


def _render_main_menu() -> str:
    return """screen main_menu():
    tag menu

    # Background image fallback to solid color
    if renpy.loadable("images/ui/main_menu_bg.png"):
        add "images/ui/main_menu_bg.png"
    else:
        add Solid("#10151c")

    # Game title
    text _("你的游戏标题"):
        xalign 0.5
        yalign 0.25
        size 72
        color "#ffffff"
        outlines [(2, "#000000", 0, 0)]

    # Button area
    frame:
        xalign 0.5
        yalign 0.65
        background None
        padding (0, 0)

        vbox:
            spacing 24

            imagebutton:
                idle "images/ui/start_game.png"
                hover "images/ui/start_game.png"
                action Start()
            imagebutton:
                idle "images/ui/load_game.png"
                hover "images/ui/load_game.png"
                action ShowMenu("load")
            imagebutton:
                idle "images/ui/settings.png"
                hover "images/ui/settings.png"
                action ShowMenu("preferences")
            imagebutton:
                idle "images/ui/exit_game.png"
                hover "images/ui/exit_game.png"
                action ShowMenu("confirm_exit")
"""


def _render_say(manifest: ProjectManifest) -> str:
    return f"""screen say(who, what):
    style_prefix "say"

    key "mouseup_3" action Function(toggle_interface)

    if not interface_hidden:
        window:
            id "window"
            style "say_window"

            has vbox
            spacing 12

            if who is not None:
                window:
                    id "namebox"
                    style "namebox"
                    text who id "who" style "say_label"

            text what id "what" style "say_dialogue" slow_cps custom_text_cps
"""


def _render_hud() -> str:
    return """screen game_hud():
    key "mouseup_3" action Function(toggle_interface)

    if not interface_hidden:
        frame:
            xalign 0.5
            yalign 1.0

            hbox:
                spacing 12

                imagebutton:
                    idle "images/ui/SAVE.png"
                    hover "images/ui/SAVE.png"
                    action ShowMenu("save")
                imagebutton:
                    idle "images/ui/LOAD.png"
                    hover "images/ui/LOAD.png"
                    action ShowMenu("load")
                imagebutton:
                    idle "images/ui/config.png"
                    hover "images/ui/config.png"
                    action ShowMenu("preferences")
                imagebutton:
                    idle "images/ui/EXIT.png"
                    hover "images/ui/EXIT.png"
                    action ShowMenu("confirm_exit")
                imagebutton:
                    idle "images/ui/history.png"
                    hover "images/ui/history.png"
                    action ShowMenu("history_log")
                imagebutton:
                    idle "images/ui/auto.png"
                    hover "images/ui/auto.png"
                    action Function(start_auto_mode)
                imagebutton:
                    idle "images/ui/pause.png"
                    hover "images/ui/pause.png"
                    action Function(stop_auto_mode)
"""


def _render_save_load(manifest: ProjectManifest) -> str:
    return f"""screen save():
    tag menu
    use file_slot_grid("save")


screen load():
    tag menu
    use file_slot_grid("load")


screen file_slot_grid(mode):
    default total_slots = {manifest.ui.save_slot_count}

    # Semi-transparent black background overlay
    frame:
        background "#000000cc"
        xfill True
        yfill True

        # Centered panel
        frame:
            xalign 0.5
            yalign 0.5
            xsize 900
            ysize 700
            background "#1a1f2ecc"
            padding (20, 20)

            vbox:
                spacing 12

                # Title
                if mode == "save":
                    text _("保存游戏") xalign 0.5 size 32
                else:
                    text _("读取游戏") xalign 0.5 size 32

                # Save slot list
                viewport:
                    scrollbars "vertical"
                    mousewheel True
                    xfill True
                    yfill True

                    grid 1 total_slots:
                        spacing 8
                        xfill True

                        for slot_index in range(1, total_slots + 1):
                            $ slot_name = str(slot_index)

                            button:
                                xfill True
                                yminimum 80
                                background "#2a3040"
                                hover_background "#3a5070"

                                if mode == "save":
                                    action Function(save_or_confirm, slot_name)
                                else:
                                    action FileAction(slot_name)

                                hbox:
                                    spacing 20
                                    xfill True
                                    yalign 0.5

                                    text _("存档 {{slot}}".format(slot=slot_index)) size 24
                                    text FileTime(slot_name, format="%Y-%m-%d %H:%M", empty=_("空槽位")) size 20 color "#888888"

                # Return button
                imagebutton:
                    idle "images/ui/back.png"
                    hover "images/ui/back.png"
                    action Return()
                    xalign 0.5
"""


def _render_preferences() -> str:
    return """screen preferences():
    tag menu

    # Semi-transparent black background overlay
    frame:
        background "#000000cc"
        xfill True
        yfill True

        # Centered panel
        frame:
            xalign 0.5
            yalign 0.5
            xsize 700
            ysize 600
            background "#1a1f2ecc"
            padding (30, 30)

            vbox:
                spacing 20
                xfill True

                text _("游戏设置") xalign 0.5 size 32

                # Volume settings
                text _("音量") size 24

                hbox:
                    spacing 12
                    yalign 0.5
                    text _("背景音乐") xsize 120
                    bar value Preference("music volume") xfill True

                hbox:
                    spacing 12
                    yalign 0.5
                    text _("人物配音") xsize 120
                    bar value Preference("voice volume") xfill True

                hbox:
                    spacing 12
                    yalign 0.5
                    text _("界面音效") xsize 120
                    bar value Preference("sound volume") xfill True

                null height 20

                # Speed settings
                text _("速度") size 24

                hbox:
                    spacing 12
                    yalign 0.5
                    text _("自动播放") xsize 120
                    bar value VariableValue("custom_auto_forward_seconds", 1.0, 30.0, step=0.5) xfill True
                    text "[custom_auto_forward_seconds:.1f] 秒" xsize 80

                hbox:
                    spacing 12
                    yalign 0.5
                    text _("文字显示") xsize 120
                    bar value VariableValue("custom_seconds_per_char", 0.01, 0.50, step=0.01) xfill True
                    text "[custom_seconds_per_char:.2f] 秒/字" xsize 100

                null height 30

                # Apply buttons
                hbox:
                    spacing 20
                    xalign 0.5
                    imagebutton:
                        idle "images/ui/apply.png"
                        hover "images/ui/apply.png"
                        action [Function(set_auto_forward_seconds, custom_auto_forward_seconds), Function(set_text_seconds_per_char, custom_seconds_per_char)]
                    imagebutton:
                        idle "images/ui/back.png"
                        hover "images/ui/back.png"
                        action Return()
"""


def _render_history(manifest: ProjectManifest) -> str:
    return f"""screen history_log():
    tag menu

    # Semi-transparent black background overlay
    frame:
        background "#000000cc"
        xfill True
        yfill True

        # Centered panel
        frame:
            xalign 0.5
            yalign 0.5
            xsize 900
            ysize 700
            background "#1a1f2ecc"
            padding (30, 30)

            vbox:
                spacing 16
                xfill True

                text _("历史记录") xalign 0.5 size 32

                # History list
                viewport:
                    scrollbars "vertical"
                    mousewheel True
                    draggable True
                    xfill True
                    yfill True

                    vbox:
                        spacing 10
                        xfill True

                        if _history_list:
                            for history_entry in _history_list[-{manifest.ui.history_length}:]:
                                hbox:
                                    spacing 8
                                    xfill True

                                    if history_entry.who:
                                        text "[history_entry.who]" size 20 color "#88ccff" yalign 0.0
                                    else:
                                        text _("旁白") size 20 color "#888888" yalign 0.0

                                    text ": [history_entry.what]" size 20 color "#dddddd"
                        else:
                            text _("暂无历史记录") xalign 0.5 color "#888888"

                imagebutton:
                    idle "images/ui/back.png"
                    hover "images/ui/back.png"
                    action Return()
                    xalign 0.5
"""


def _render_confirm() -> str:
    return """screen confirm_exit():
    modal True

    frame:
        xalign 0.5
        yalign 0.5

        vbox:
            spacing 12

            text _("Exit the game?")
            hbox:
                spacing 12
                imagebutton:
                    idle "images/ui/confirm.png"
                    hover "images/ui/confirm.png"
                    action Quit(confirm=False)
                imagebutton:
                    idle "images/ui/cancel.png"
                    hover "images/ui/cancel.png"
                    action Hide("confirm_exit")


screen confirm_save_overwrite(slot_name):
    modal True

    frame:
        xalign 0.5
        yalign 0.5

        vbox:
            spacing 12

            text _("Overwrite")
            text _("Overwrite save slot [slot_name]?")
            hbox:
                spacing 12
                imagebutton:
                    idle "images/ui/overwrite.png"
                    hover "images/ui/overwrite.png"
                    action [Function(overwrite_save, slot_name), Hide("confirm_save_overwrite")]
                imagebutton:
                    idle "images/ui/cancel.png"
                    hover "images/ui/cancel.png"
                    action Hide("confirm_save_overwrite")
"""


def _render_prologue() -> str:
    return """label start:
    show screen game_hud

    scene bg demo_room with bg_fade
    show char hero default at char_move_in_left

    $ safe_play_music("audio/music/demo_bgm.mp3", fadein=1.0)
    hero "The phase-1 scaffold is alive."

    $ safe_play_voice("audio/voice/hero_001.wav")
    hero "This vertical slice wires menus, save hooks, history, autoplay settings, and placeholder animation seams."

    menu:
        "Open the system demo.":
            jump system_demo
        "End the slice.":
            return


label system_demo:
    hero "Use SAVE, LOAD, CONFIG, EXIT, History, Auto, and Pause from the generated HUD placeholders."
    return
"""
